"""Pure domain layer: money, dates, records, statuses, errors. No framework imports."""

from jettae.domain.errors import (
    ConservationError,
    CurrencyMismatchError,
    DomainValidationError,
    InvalidMoneyError,
    JettaeError,
    NotFoundError,
    ReportValidityError,
    RuleNotFoundError,
    StaleResultError,
    TenantMismatchError,
)
from jettae.domain.hashing import canonical_json, content_hash
from jettae.domain.models import (
    Agreement,
    Allocation,
    Approval,
    BankTxn,
    Change,
    Computation,
    Decision,
    DocumentVersion,
    Fact,
    Invoice,
    RecomputePlan,
    SettlementLine,
    SourceSpan,
)
from jettae.domain.money import Money, RoundingMode, round_to_int, sum_money
from jettae.domain.status import (
    ChangeKind,
    DocKind,
    DocumentStatus,
    LineKind,
    ReconcileStatus,
    ReviewStatus,
    TradeType,
)

__all__ = [
    "Agreement",
    "Allocation",
    "Approval",
    "BankTxn",
    "Change",
    "ChangeKind",
    "Computation",
    "ConservationError",
    "CurrencyMismatchError",
    "Decision",
    "DocKind",
    "DocumentStatus",
    "DocumentVersion",
    "DomainValidationError",
    "Fact",
    "InvalidMoneyError",
    "Invoice",
    "JettaeError",
    "LineKind",
    "Money",
    "NotFoundError",
    "RecomputePlan",
    "ReconcileStatus",
    "ReportValidityError",
    "ReviewStatus",
    "RoundingMode",
    "RuleNotFoundError",
    "SettlementLine",
    "SourceSpan",
    "StaleResultError",
    "TenantMismatchError",
    "TradeType",
    "canonical_json",
    "content_hash",
    "round_to_int",
    "sum_money",
]
